using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SAP.Middleware.Connector;

namespace rfcBaika
{
    public class ZMOV_QUERY_DET_FACT
    {
        public responce_ZMOV_QUERY_DET_FACT sapRun(request_ZMOV_QUERY_DET_FACT import)
        {
            RfcDestination configSap = RfcDestinationManager.GetDestination("DDC");
            RfcRepository SapRfcRepository = configSap.Repository;
            IRfcFunction rfcFunction = SapRfcRepository.CreateFunction("ZMOV_QUERY_DET_FACT");

            
            IRfcTable rfcTable_I_VBELN_I = rfcFunction.GetTable("I_VBELN");
            foreach (ZMOV_QUERY_DET_FACT_I_VBELN row in import.I_VBELN)
            {
                rfcTable_I_VBELN_I.Append();
                ZMOV_QUERY_DET_FACT_I_VBELN datoTabla = new ZMOV_QUERY_DET_FACT_I_VBELN();
                rfcTable_I_VBELN_I.SetValue("SIGN", row.SIGN);
                rfcTable_I_VBELN_I.SetValue("OPTION", row.OPTION);
                rfcTable_I_VBELN_I.SetValue("LOW", row.LOW);
                rfcTable_I_VBELN_I.SetValue("HIGH", row.HIGH);
            }
            rfcFunction.SetValue("I_VBELN", rfcTable_I_VBELN_I);
            rfcFunction.Invoke(configSap);
            //string aa = rfcFunction.ToString();
            responce_ZMOV_QUERY_DET_FACT res = new responce_ZMOV_QUERY_DET_FACT();
            //IRfcTable rfcTable_I_VBELN = rfcFunction.GetTable("I_VBELN");
            //res.I_VBELN = new ZMOV_QUERY_DET_FACT_I_VBELN[rfcTable_I_VBELN.RowCount];
            //int i_I_VBELN = 0;
            //foreach (IRfcStructure row in rfcTable_I_VBELN)
            //{
            //    ZMOV_QUERY_DET_FACT_I_VBELN datoTabla = new ZMOV_QUERY_DET_FACT_I_VBELN();
            //    datoTabla.SIGN = row.GetString("SIGN");
            //    datoTabla.OPTION = row.GetString("OPTION");
            //    datoTabla.LOW = row.GetString("LOW");
            //    datoTabla.HIGH = row.GetString("HIGH");
            //    res.I_VBELN[i_I_VBELN] = datoTabla; ++i_I_VBELN;
            //}
            IRfcTable rfcTable_LOG = rfcFunction.GetTable("LOG");
            res.LOG = new ZMOV_QUERY_DET_FACT_LOG[rfcTable_LOG.RowCount];
            int i_LOG = 0;
            foreach (IRfcStructure row in rfcTable_LOG)
            {
                ZMOV_QUERY_DET_FACT_LOG datoTabla = new ZMOV_QUERY_DET_FACT_LOG();
                datoTabla.TYPE = row.GetString("TYPE");
                datoTabla.ID = row.GetString("ID");
                datoTabla.NUMBER = row.GetInt("NUMBER");
                datoTabla.MESSAGE = row.GetString("MESSAGE");
                datoTabla.LOG_NO = row.GetString("LOG_NO");
                datoTabla.LOG_MSG_NO = row.GetInt("LOG_MSG_NO");
                datoTabla.MESSAGE_V1 = row.GetString("MESSAGE_V1");
                datoTabla.MESSAGE_V2 = row.GetString("MESSAGE_V2");
                datoTabla.MESSAGE_V3 = row.GetString("MESSAGE_V3");
                datoTabla.MESSAGE_V4 = row.GetString("MESSAGE_V4");
                datoTabla.PARAMETER = row.GetString("PARAMETER");
                datoTabla.ROW = row.GetInt("ROW");
                datoTabla.FIELD = row.GetString("FIELD");
                datoTabla.SYSTEM = row.GetString("SYSTEM");
                res.LOG[i_LOG] = datoTabla; ++i_LOG;
            }
            IRfcTable rfcTable_LT_KONV = rfcFunction.GetTable("LT_KONV");
            res.LT_KONV = new ZMOV_QUERY_DET_FACT_LT_KONV[rfcTable_LT_KONV.RowCount];
            int i_LT_KONV = 0;
            foreach (IRfcStructure row in rfcTable_LT_KONV)
            {
                ZMOV_QUERY_DET_FACT_LT_KONV datoTabla = new ZMOV_QUERY_DET_FACT_LT_KONV();
                datoTabla.MANDT = row.GetString("MANDT");
                datoTabla.KNUMV = row.GetString("KNUMV");
                datoTabla.KPOSN = row.GetInt("KPOSN");

                //datoTabla.STUNR = row.GetInt("STUNR");
                //datoTabla.ZAEHK = row.GetInt("ZAEHK");
                //datoTabla.KAPPL = row.GetString("KAPPL");
                datoTabla.KSCHL = row.GetString("KSCHL");
                //datoTabla.KDATU = row.GetString("KDATU");
                //datoTabla.KRECH = row.GetString("KRECH");
                datoTabla.KAWRT = row.GetDecimal("KAWRT");
                datoTabla.KBETR = row.GetDecimal("KBETR");
                //datoTabla.WAERS = row.GetString("WAERS");
                //datoTabla.KKURS = row.GetDecimal("KKURS");
                //datoTabla.KPEIN = row.GetDecimal("KPEIN");
                //datoTabla.KMEIN = row.GetString("KMEIN");
                //datoTabla.KUMZA = row.GetDecimal("KUMZA");
                //datoTabla.KUMNE = row.GetDecimal("KUMNE");
                //datoTabla.KNTYP = row.GetString("KNTYP");
                
                datoTabla.KSTAT = row.GetString("KSTAT");
                
                //datoTabla.KNPRS = row.GetString("KNPRS");
                //datoTabla.KRUEK = row.GetString("KRUEK");
                //datoTabla.KRELI = row.GetString("KRELI");
                //datoTabla.KHERK = row.GetString("KHERK");
                //datoTabla.KGRPE = row.GetString("KGRPE");
                //datoTabla.KOUPD = row.GetString("KOUPD");
                //datoTabla.KOLNR = row.GetInt("KOLNR");
                //datoTabla.KNUMH = row.GetString("KNUMH");
                //datoTabla.KOPOS = row.GetInt("KOPOS");
                //datoTabla.KVSL1 = row.GetString("KVSL1");
                //datoTabla.SAKN1 = row.GetString("SAKN1");
                //datoTabla.MWSK1 = row.GetString("MWSK1");
                //datoTabla.KVSL2 = row.GetString("KVSL2");
                //datoTabla.SAKN2 = row.GetString("SAKN2");
                //datoTabla.MWSK2 = row.GetString("MWSK2");
                //datoTabla.LIFNR = row.GetString("LIFNR");
                //datoTabla.KUNNR = row.GetString("KUNNR");
                //datoTabla.KDIFF = row.GetDecimal("KDIFF");
                //datoTabla.KWERT = row.GetDecimal("KWERT");
                //datoTabla.KSTEU = row.GetString("KSTEU");
                //datoTabla.KINAK = row.GetString("KINAK");
                //datoTabla.KOAID = row.GetString("KOAID");
                //datoTabla.ZAEKO = row.GetInt("ZAEKO");
                //datoTabla.KMXAW = row.GetString("KMXAW");
                //datoTabla.KMXWR = row.GetString("KMXWR");
                //datoTabla.KFAKTOR = row.GetDouble("KFAKTOR");
                //datoTabla.KDUPL = row.GetString("KDUPL");
                //datoTabla.KFAKTOR1 = row.GetDouble("KFAKTOR1");
                //datoTabla.KZBZG = row.GetString("KZBZG");
                //datoTabla.KSTBS = row.GetDecimal("KSTBS");
                //datoTabla.KONMS = row.GetString("KONMS");
                //datoTabla.KONWS = row.GetString("KONWS");
                //datoTabla.KAWRT_K = row.GetDecimal("KAWRT_K");
                //datoTabla.KWAEH = row.GetString("KWAEH");
                //datoTabla.KWERT_K = row.GetDecimal("KWERT_K");
                //datoTabla.KFKIV = row.GetString("KFKIV");
                //datoTabla.KVARC = row.GetString("KVARC");
                //datoTabla.KMPRS = row.GetString("KMPRS");
                //datoTabla.PRSQU = row.GetString("PRSQU");
                //datoTabla.VARCOND = row.GetString("VARCOND");
                datoTabla.STUFE = row.GetDecimal("STUFE");
                //datoTabla.WEGXX = row.GetDecimal("WEGXX");
                //datoTabla.KTREL = row.GetString("KTREL");
                //datoTabla.MDFLG = row.GetString("MDFLG");
                //datoTabla.TXJLV = row.GetString("TXJLV");
                //datoTabla.KBFLAG = row.GetString("KBFLAG");
                //datoTabla.KOLNR3 = row.GetInt("KOLNR3");
                //datoTabla.CPF_GUID = row.GetString("CPF_GUID");
                //datoTabla.KAQTY = row.GetString("KAQTY");
                res.LT_KONV[i_LT_KONV] = datoTabla; ++i_LT_KONV;
            }
            IRfcTable rfcTable_LT_VBRK = rfcFunction.GetTable("LT_VBRK");
            res.LT_VBRK = new ZMOV_QUERY_DET_FACT_LT_VBRK[rfcTable_LT_VBRK.RowCount];
            int i_LT_VBRK = 0;
            foreach (IRfcStructure row in rfcTable_LT_VBRK)
            {
                ZMOV_QUERY_DET_FACT_LT_VBRK datoTabla = new ZMOV_QUERY_DET_FACT_LT_VBRK();
                datoTabla.MANDT = row.GetString("MANDT");
                datoTabla.VBELN = row.GetString("VBELN");
                datoTabla.FKART = row.GetString("FKART");
                datoTabla.FKTYP = row.GetString("FKTYP");
                datoTabla.VBTYP = row.GetString("VBTYP");
                datoTabla.WAERK = row.GetString("WAERK");
                datoTabla.VKORG = row.GetString("VKORG");
                datoTabla.VTWEG = row.GetString("VTWEG");
                //datoTabla.KALSM = row.GetString("KALSM");
                datoTabla.KNUMV = row.GetString("KNUMV");
                //datoTabla.VSBED = row.GetString("VSBED");
                datoTabla.FKDAT = row.GetString("FKDAT");
                //datoTabla.BELNR = row.GetString("BELNR");
                //datoTabla.GJAHR = row.GetInt("GJAHR");
                datoTabla.POPER = row.GetInt("POPER");
                //datoTabla.KONDA = row.GetString("KONDA");
                //datoTabla.KDGRP = row.GetString("KDGRP");
                //datoTabla.BZIRK = row.GetString("BZIRK");
                //datoTabla.PLTYP = row.GetString("PLTYP");
                datoTabla.INCO1 = row.GetString("INCO1");
                datoTabla.INCO2 = row.GetString("INCO2");
                //datoTabla.EXPKZ = row.GetString("EXPKZ");
                //datoTabla.RFBSK = row.GetString("RFBSK");
                //datoTabla.MRNKZ = row.GetString("MRNKZ");
                datoTabla.KURRF = row.GetDecimal("KURRF");
                //datoTabla.CPKUR = row.GetString("CPKUR");
                //datoTabla.VALTG = row.GetInt("VALTG");
                //datoTabla.VALDT = row.GetString("VALDT");
                datoTabla.ZTERM = row.GetString("ZTERM");
                //datoTabla.ZLSCH = row.GetString("ZLSCH");
                //datoTabla.KTGRD = row.GetString("KTGRD");
                //datoTabla.LAND1 = row.GetString("LAND1");
                //datoTabla.REGIO = row.GetString("REGIO");
                //datoTabla.COUNC = row.GetString("COUNC");
                //datoTabla.CITYC = row.GetString("CITYC");
                //datoTabla.BUKRS = row.GetString("BUKRS");
                //datoTabla.TAXK1 = row.GetString("TAXK1");
                //datoTabla.TAXK2 = row.GetString("TAXK2");
                //datoTabla.TAXK3 = row.GetString("TAXK3");
                //datoTabla.TAXK4 = row.GetString("TAXK4");
                //datoTabla.TAXK5 = row.GetString("TAXK5");
                //datoTabla.TAXK6 = row.GetString("TAXK6");
                //datoTabla.TAXK7 = row.GetString("TAXK7");
                //datoTabla.TAXK8 = row.GetString("TAXK8");
                //datoTabla.TAXK9 = row.GetString("TAXK9");
                datoTabla.NETWR = row.GetDecimal("NETWR");
                //datoTabla.ZUKRI = row.GetString("ZUKRI");
                //datoTabla.ERNAM = row.GetString("ERNAM");
                //datoTabla.ERZET = row.GetString("ERZET");
                //datoTabla.ERDAT = row.GetString("ERDAT");
                //datoTabla.STAFO = row.GetString("STAFO");
                datoTabla.KUNRG = row.GetString("KUNRG");
                datoTabla.KUNAG = row.GetString("KUNAG");
                //datoTabla.MABER = row.GetString("MABER");
                datoTabla.STWAE = row.GetString("STWAE");
                //datoTabla.EXNUM = row.GetString("EXNUM");
                //datoTabla.STCEG = row.GetString("STCEG");
                //datoTabla.AEDAT = row.GetString("AEDAT");
                //datoTabla.SFAKN = row.GetString("SFAKN");
                //datoTabla.KNUMA = row.GetString("KNUMA");
                //datoTabla.FKART_RL = row.GetString("FKART_RL");
                //datoTabla.FKDAT_RL = row.GetString("FKDAT_RL");
                //datoTabla.KURST = row.GetString("KURST");
                //datoTabla.MSCHL = row.GetString("MSCHL");
                //datoTabla.MANSP = row.GetString("MANSP");
                //datoTabla.SPART = row.GetString("SPART");
                //datoTabla.KKBER = row.GetString("KKBER");
                //datoTabla.KNKLI = row.GetString("KNKLI");
                //datoTabla.CMWAE = row.GetString("CMWAE");
                //datoTabla.CMKUF = row.GetDecimal("CMKUF");
                //datoTabla.HITYP_PR = row.GetString("HITYP_PR");
                //datoTabla.BSTNK_VF = row.GetString("BSTNK_VF");
                //datoTabla.VBUND = row.GetString("VBUND");
                //datoTabla.FKART_AB = row.GetString("FKART_AB");
                //datoTabla.KAPPL = row.GetString("KAPPL");
                //datoTabla.LANDTX = row.GetString("LANDTX");
                //datoTabla.STCEG_H = row.GetString("STCEG_H");
                //datoTabla.STCEG_L = row.GetString("STCEG_L");
                datoTabla.XBLNR = row.GetString("XBLNR");
                datoTabla.ZUONR = row.GetString("ZUONR");
                //datoTabla.MWSBK = row.GetDecimal("MWSBK");
                //datoTabla.LOGSYS = row.GetString("LOGSYS");
                //datoTabla.FKSTO = row.GetString("FKSTO");
                //datoTabla.XEGDR = row.GetString("XEGDR");
                //datoTabla.RPLNR = row.GetString("RPLNR");
                //datoTabla.LCNUM = row.GetString("LCNUM");
                //datoTabla.J_1AFITP = row.GetString("J_1AFITP");
                //datoTabla.KURRF_DAT = row.GetString("KURRF_DAT");
                //datoTabla.AKWAE = row.GetString("AKWAE");
                //datoTabla.AKKUR = row.GetDecimal("AKKUR");
                datoTabla.KIDNO = row.GetString("KIDNO");
                //datoTabla.BVTYP = row.GetString("BVTYP");
                //datoTabla.NUMPG = row.GetInt("NUMPG");
                //datoTabla.BUPLA = row.GetString("BUPLA");
                //datoTabla.VKONT = row.GetString("VKONT");
                //datoTabla.FKK_DOCSTAT = row.GetString("FKK_DOCSTAT");
                //datoTabla.NRZAS = row.GetString("NRZAS");
                //datoTabla.SPE_BILLING_IND = row.GetString("SPE_BILLING_IND");
                //datoTabla.VTREF = row.GetString("VTREF");
                //datoTabla.FK_SOURCE_SYS = row.GetString("FK_SOURCE_SYS");
                //datoTabla.FKTYP_CRM = row.GetString("FKTYP_CRM");
                //datoTabla.STGRD = row.GetString("STGRD");
                //datoTabla.VBTYP_EXT = row.GetString("VBTYP_EXT");
                //datoTabla.J_1TPBUPL = row.GetString("J_1TPBUPL");
                //datoTabla.INCOV = row.GetString("INCOV");
                //datoTabla.INCO2_L = row.GetString("INCO2_L");
                //datoTabla.INCO3_L = row.GetString("INCO3_L");
                //datoTabla.DPC_REL = row.GetString("DPC_REL");
                //datoTabla.MNDID = row.GetString("MNDID");
                //datoTabla.PAY_TYPE = row.GetString("PAY_TYPE");
                //datoTabla.SEPON = row.GetString("SEPON");
                //datoTabla.MNDVG = row.GetString("MNDVG");
                //datoTabla.SPPAYM = row.GetString("SPPAYM");
                //datoTabla.SPPORD = row.GetString("SPPORD");
                res.LT_VBRK[i_LT_VBRK] = datoTabla; ++i_LT_VBRK;
            }
            IRfcTable rfcTable_LT_VBRP = rfcFunction.GetTable("LT_VBRP");
            res.LT_VBRP = new ZMOV_QUERY_DET_FACT_LT_VBRP[rfcTable_LT_VBRP.RowCount];
            int i_LT_VBRP = 0;
            foreach (IRfcStructure row in rfcTable_LT_VBRP)
            {
                ZMOV_QUERY_DET_FACT_LT_VBRP datoTabla = new ZMOV_QUERY_DET_FACT_LT_VBRP();
                datoTabla.MANDT = row.GetString("MANDT");
                datoTabla.VBELN = row.GetString("VBELN");
                datoTabla.POSNR = row.GetInt("POSNR");
                //datoTabla.UEPOS = row.GetInt("UEPOS");
                datoTabla.FKIMG = row.GetDecimal("FKIMG");
                datoTabla.VRKME = row.GetString("VRKME");
                //datoTabla.UMVKZ = row.GetDecimal("UMVKZ");
                //datoTabla.UMVKN = row.GetDecimal("UMVKN");
                datoTabla.MEINS = row.GetString("MEINS");
                //datoTabla.SMENG = row.GetDecimal("SMENG");
                datoTabla.FKLMG = row.GetDecimal("FKLMG");
                datoTabla.LMENG = row.GetDecimal("LMENG");
                datoTabla.NTGEW = row.GetDecimal("NTGEW");
                datoTabla.BRGEW = row.GetDecimal("BRGEW");
                datoTabla.GEWEI = row.GetString("GEWEI");
                //datoTabla.VOLUM = row.GetDecimal("VOLUM");
                //datoTabla.VOLEH = row.GetString("VOLEH");
                //datoTabla.GSBER = row.GetString("GSBER");
                datoTabla.PRSDT = row.GetString("PRSDT");
                datoTabla.FBUDA = row.GetString("FBUDA");
                datoTabla.KURSK = row.GetDecimal("KURSK");
                datoTabla.NETWR = row.GetDecimal("NETWR");
                //datoTabla.VBELV = row.GetString("VBELV");
                //datoTabla.POSNV = row.GetInt("POSNV");
                //datoTabla.VGBEL = row.GetString("VGBEL");
                //datoTabla.VGPOS = row.GetInt("VGPOS");
                //datoTabla.VGTYP = row.GetString("VGTYP");
                datoTabla.AUBEL = row.GetString("AUBEL");
                datoTabla.AUPOS = row.GetInt("AUPOS");
                datoTabla.AUREF = row.GetString("AUREF");
                datoTabla.MATNR = row.GetString("MATNR");
                datoTabla.ARKTX = row.GetString("ARKTX");
                //datoTabla.PMATN = row.GetString("PMATN");
                datoTabla.CHARG = row.GetString("CHARG");
                datoTabla.MATKL = row.GetString("MATKL");
                datoTabla.PSTYV = row.GetString("PSTYV");
                //datoTabla.POSAR = row.GetString("POSAR");
                //datoTabla.PRODH = row.GetString("PRODH");
                //datoTabla.VSTEL = row.GetString("VSTEL");
                //datoTabla.ATPKZ = row.GetString("ATPKZ");
                //datoTabla.SPART = row.GetString("SPART");
                //datoTabla.POSPA = row.GetInt("POSPA");
                datoTabla.WERKS = row.GetString("WERKS");
                datoTabla.ALAND = row.GetString("ALAND");
                //datoTabla.WKREG = row.GetString("WKREG");
                //datoTabla.WKCOU = row.GetString("WKCOU");
                //datoTabla.WKCTY = row.GetString("WKCTY");
                //datoTabla.TAXM1 = row.GetString("TAXM1");
                //datoTabla.TAXM2 = row.GetString("TAXM2");
                //datoTabla.TAXM3 = row.GetString("TAXM3");
                //datoTabla.TAXM4 = row.GetString("TAXM4");
                //datoTabla.TAXM5 = row.GetString("TAXM5");
                //datoTabla.TAXM6 = row.GetString("TAXM6");
                //datoTabla.TAXM7 = row.GetString("TAXM7");
                //datoTabla.TAXM8 = row.GetString("TAXM8");
                //datoTabla.TAXM9 = row.GetString("TAXM9");
                //datoTabla.KOWRR = row.GetString("KOWRR");
                //datoTabla.PRSFD = row.GetString("PRSFD");
                //datoTabla.SKTOF = row.GetString("SKTOF");
                //datoTabla.SKFBP = row.GetDecimal("SKFBP");
                //datoTabla.KONDM = row.GetString("KONDM");
                //datoTabla.KTGRM = row.GetString("KTGRM");
                //datoTabla.KOSTL = row.GetString("KOSTL");
                //datoTabla.BONUS = row.GetString("BONUS");
                //datoTabla.PROVG = row.GetString("PROVG");
                //datoTabla.EANNR = row.GetString("EANNR");
                //datoTabla.VKGRP = row.GetString("VKGRP");
                //datoTabla.VKBUR = row.GetString("VKBUR");
                //datoTabla.SPARA = row.GetString("SPARA");
                //datoTabla.SHKZG = row.GetString("SHKZG");
                //datoTabla.ERNAM = row.GetString("ERNAM");
                //datoTabla.ERDAT = row.GetString("ERDAT");
                //datoTabla.ERZET = row.GetString("ERZET");
                //datoTabla.BWTAR = row.GetString("BWTAR");
                //datoTabla.LGORT = row.GetString("LGORT");
                //datoTabla.STAFO = row.GetString("STAFO");
                //datoTabla.WAVWR = row.GetDecimal("WAVWR");
                //datoTabla.KZWI1 = row.GetDecimal("KZWI1");
                //datoTabla.KZWI2 = row.GetDecimal("KZWI2");
                //datoTabla.KZWI3 = row.GetDecimal("KZWI3");
                //datoTabla.KZWI4 = row.GetDecimal("KZWI4");
                //datoTabla.KZWI5 = row.GetDecimal("KZWI5");
                //datoTabla.KZWI6 = row.GetDecimal("KZWI6");
                //datoTabla.STCUR = row.GetDecimal("STCUR");
                //datoTabla.UVPRS = row.GetString("UVPRS");
                //datoTabla.UVALL = row.GetString("UVALL");
                //datoTabla.EAN11 = row.GetString("EAN11");
                //datoTabla.PRCTR = row.GetString("PRCTR");
                //datoTabla.KVGR1 = row.GetString("KVGR1");
                //datoTabla.KVGR2 = row.GetString("KVGR2");
                //datoTabla.KVGR3 = row.GetString("KVGR3");
                //datoTabla.KVGR4 = row.GetString("KVGR4");
                //datoTabla.KVGR5 = row.GetString("KVGR5");
                //datoTabla.MVGR1 = row.GetString("MVGR1");
                //datoTabla.MVGR2 = row.GetString("MVGR2");
                //datoTabla.MVGR3 = row.GetString("MVGR3");
                //datoTabla.MVGR4 = row.GetString("MVGR4");
                //datoTabla.MVGR5 = row.GetString("MVGR5");
                //datoTabla.MATWA = row.GetString("MATWA");
                //datoTabla.BONBA = row.GetDecimal("BONBA");
                //datoTabla.KOKRS = row.GetString("KOKRS");
                //datoTabla.PAOBJNR = row.GetInt("PAOBJNR");
                //datoTabla.PS_PSP_PNR = row.GetInt("PS_PSP_PNR");
                //datoTabla.AUFNR = row.GetString("AUFNR");
                //datoTabla.TXJCD = row.GetString("TXJCD");
                //datoTabla.CMPRE = row.GetDecimal("CMPRE");
                //datoTabla.CMPNT = row.GetString("CMPNT");
                //datoTabla.CUOBJ = row.GetInt("CUOBJ");
                //datoTabla.CUOBJ_CH = row.GetInt("CUOBJ_CH");
                //datoTabla.KOUPD = row.GetString("KOUPD");
                //datoTabla.UECHA = row.GetInt("UECHA");
                //datoTabla.XCHAR = row.GetString("XCHAR");
                //datoTabla.ABRVW = row.GetString("ABRVW");
                //datoTabla.SERNR = row.GetString("SERNR");
                //datoTabla.BZIRK_AUFT = row.GetString("BZIRK_AUFT");
                //datoTabla.KDGRP_AUFT = row.GetString("KDGRP_AUFT");
                //datoTabla.KONDA_AUFT = row.GetString("KONDA_AUFT");
                //datoTabla.LLAND_AUFT = row.GetString("LLAND_AUFT");
                //datoTabla.MPROK = row.GetString("MPROK");
                //datoTabla.PLTYP_AUFT = row.GetString("PLTYP_AUFT");
                //datoTabla.REGIO_AUFT = row.GetString("REGIO_AUFT");
                //datoTabla.VKORG_AUFT = row.GetString("VKORG_AUFT");
                //datoTabla.VTWEG_AUFT = row.GetString("VTWEG_AUFT");
                //datoTabla.ABRBG = row.GetString("ABRBG");
                //datoTabla.PROSA = row.GetString("PROSA");
                //datoTabla.UEPVW = row.GetString("UEPVW");
                //datoTabla.AUTYP = row.GetString("AUTYP");
                //datoTabla.STADAT = row.GetString("STADAT");
                //datoTabla.FPLNR = row.GetString("FPLNR");
                //datoTabla.FPLTR = row.GetInt("FPLTR");
                //datoTabla.AKTNR = row.GetString("AKTNR");
                //datoTabla.KNUMA_PI = row.GetString("KNUMA_PI");
                //datoTabla.KNUMA_AG = row.GetString("KNUMA_AG");
                //datoTabla.PREFE = row.GetString("PREFE");
                //datoTabla.MWSBP = row.GetDecimal("MWSBP");
                //datoTabla.AUGRU_AUFT = row.GetString("AUGRU_AUFT");
                //datoTabla.FAREG = row.GetString("FAREG");
                //datoTabla.UPMAT = row.GetString("UPMAT");
                //datoTabla.UKONM = row.GetString("UKONM");
                //datoTabla.CMPRE_FLT = row.GetDouble("CMPRE_FLT");
                //datoTabla.ABFOR = row.GetString("ABFOR");
                //datoTabla.ABGES = row.GetDouble("ABGES");
                //datoTabla.J_1ARFZ = row.GetString("J_1ARFZ");
                //datoTabla.J_1AREGIO = row.GetString("J_1AREGIO");
                //datoTabla.J_1AGICD = row.GetString("J_1AGICD");
                //datoTabla.J_1ADTYP = row.GetString("J_1ADTYP");
                //datoTabla.J_1ATXREL = row.GetString("J_1ATXREL");
                //datoTabla.J_1BCFOP = row.GetString("J_1BCFOP");
                //datoTabla.J_1BTAXLW1 = row.GetString("J_1BTAXLW1");
                //datoTabla.J_1BTAXLW2 = row.GetString("J_1BTAXLW2");
                //datoTabla.J_1BTXSDC = row.GetString("J_1BTXSDC");
                //datoTabla.BRTWR = row.GetDecimal("BRTWR");
                //datoTabla.WKTNR = row.GetString("WKTNR");
                //datoTabla.WKTPS = row.GetInt("WKTPS");
                //datoTabla.RPLNR = row.GetString("RPLNR");
                //datoTabla.KURSK_DAT = row.GetString("KURSK_DAT");
                //datoTabla.WGRU1 = row.GetString("WGRU1");
                //datoTabla.WGRU2 = row.GetString("WGRU2");
                //datoTabla.KDKG1 = row.GetString("KDKG1");
                //datoTabla.KDKG2 = row.GetString("KDKG2");
                //datoTabla.KDKG3 = row.GetString("KDKG3");
                //datoTabla.KDKG4 = row.GetString("KDKG4");
                //datoTabla.KDKG5 = row.GetString("KDKG5");
                //datoTabla.VKAUS = row.GetString("VKAUS");
                //datoTabla.J_1AINDXP = row.GetString("J_1AINDXP");
                //datoTabla.J_1AIDATEP = row.GetString("J_1AIDATEP");
                //datoTabla.KZFME = row.GetString("KZFME");
                //datoTabla.MWSKZ = row.GetString("MWSKZ");
                //datoTabla.VERTT = row.GetString("VERTT");
                //datoTabla.VERTN = row.GetString("VERTN");
                //datoTabla.SGTXT = row.GetString("SGTXT");
                //datoTabla.DELCO = row.GetString("DELCO");
                //datoTabla.BEMOT = row.GetString("BEMOT");
                //datoTabla.RRREL = row.GetString("RRREL");
                //datoTabla.AKKUR = row.GetDecimal("AKKUR");
                //datoTabla.WMINR = row.GetString("WMINR");
                //datoTabla.VGBEL_EX = row.GetString("VGBEL_EX");
                //datoTabla.VGPOS_EX = row.GetInt("VGPOS_EX");
                //datoTabla.LOGSYS = row.GetString("LOGSYS");
                //datoTabla.VGTYP_EX = row.GetString("VGTYP_EX");
                //datoTabla.J_1BTAXLW3 = row.GetString("J_1BTAXLW3");
                //datoTabla.J_1BTAXLW4 = row.GetString("J_1BTAXLW4");
                //datoTabla.J_1BTAXLW5 = row.GetString("J_1BTAXLW5");
                //datoTabla.MSR_ID = row.GetString("MSR_ID");
                //datoTabla.MSR_REFUND_CODE = row.GetString("MSR_REFUND_CODE");
                //datoTabla.MSR_RET_REASON = row.GetString("MSR_RET_REASON");
                //datoTabla.NRAB_KNUMH = row.GetString("NRAB_KNUMH");
                //datoTabla.NRAB_VALUE = row.GetDecimal("NRAB_VALUE");
                //datoTabla.DISPUTE_CASE = row.GetString("DISPUTE_CASE");
                //datoTabla.FUND_USAGE_ITEM = row.GetString("FUND_USAGE_ITEM");
                //datoTabla.FARR_RELTYPE = row.GetString("FARR_RELTYPE");
                //datoTabla.CLAIMS_TAXATION = row.GetString("CLAIMS_TAXATION");
                //datoTabla.KURRF_DAT_ORIG = row.GetString("KURRF_DAT_ORIG");
                //datoTabla.VGTYP_EXT = row.GetString("VGTYP_EXT");
                //datoTabla.SGT_RCAT = row.GetString("SGT_RCAT");
                //datoTabla.SGT_SCAT = row.GetString("SGT_SCAT");
                //datoTabla.AUFPL = row.GetInt("AUFPL");
                //datoTabla.APLZL = row.GetInt("APLZL");
                //datoTabla.DPCNR = row.GetString("DPCNR");
                //datoTabla.DCPNR = row.GetInt("DCPNR");
                //datoTabla.DPNRB = row.GetInt("DPNRB");
                //datoTabla.PEROP_BEG = row.GetString("PEROP_BEG");
                //datoTabla.PEROP_END = row.GetString("PEROP_END");
                //datoTabla.FONDS = row.GetString("FONDS");
                //datoTabla.FISTL = row.GetString("FISTL");
                //datoTabla.FKBER = row.GetString("FKBER");
                //datoTabla.GRANT_NBR = row.GetString("GRANT_NBR");
                //datoTabla.PRS_WORK_PERIOD = row.GetInt("PRS_WORK_PERIOD");
                //datoTabla.PPRCTR = row.GetString("PPRCTR");
                //datoTabla.PARGB = row.GetString("PARGB");
                //datoTabla.AUFPL_OAA = row.GetInt("AUFPL_OAA");
                //datoTabla.APLZL_OAA = row.GetInt("APLZL_OAA");
                //datoTabla.CAMPAIGN = row.GetString("CAMPAIGN");
                //datoTabla.COMPREAS = row.GetString("COMPREAS");
                res.LT_VBRP[i_LT_VBRP] = datoTabla; ++i_LT_VBRP;
            }

            return res;
        }
    }
    public class request_ZMOV_QUERY_DET_FACT
    {
        
        public ZMOV_QUERY_DET_FACT_I_VBELN[] I_VBELN;
    }
    public class responce_ZMOV_QUERY_DET_FACT
    {
        public ZMOV_QUERY_DET_FACT_I_VBELN[] I_VBELN;
        public ZMOV_QUERY_DET_FACT_LOG[] LOG;
        public ZMOV_QUERY_DET_FACT_LT_KONV[] LT_KONV;
        public ZMOV_QUERY_DET_FACT_LT_VBRK[] LT_VBRK;
        public ZMOV_QUERY_DET_FACT_LT_VBRP[] LT_VBRP;
    }
    public class ZMOV_QUERY_DET_FACT_I_VBELN
    {
        public String SIGN;
        public String OPTION;
        public String LOW;
        public String HIGH;
    }
    public class ZMOV_QUERY_DET_FACT_LOG
    {
        public String TYPE;
        public String ID;
        public Int32 NUMBER;
        public String MESSAGE;
        public String LOG_NO;
        public Int32 LOG_MSG_NO;
        public String MESSAGE_V1;
        public String MESSAGE_V2;
        public String MESSAGE_V3;
        public String MESSAGE_V4;
        public String PARAMETER;
        public Int32 ROW;
        public String FIELD;
        public String SYSTEM;
    }
    public class ZMOV_QUERY_DET_FACT_LT_KONV
    {
        public String MANDT;
        public String KNUMV;
        public Int32 KPOSN;
        public Int32 STUNR;
        public Int32 ZAEHK;
        public String KAPPL;
        public String KSCHL;
        public String KDATU;
        public String KRECH;
        public Decimal KAWRT;
        public Decimal KBETR;
        public String WAERS;
        public Decimal KKURS;
        public Decimal KPEIN;
        public String KMEIN;
        public Decimal KUMZA;
        public Decimal KUMNE;
        public String KNTYP;
        public String KSTAT;
        public String KNPRS;
        public String KRUEK;
        public String KRELI;
        public String KHERK;
        public String KGRPE;
        public String KOUPD;
        public Int32 KOLNR;
        public String KNUMH;
        public Int32 KOPOS;
        public String KVSL1;
        public String SAKN1;
        public String MWSK1;
        public String KVSL2;
        public String SAKN2;
        public String MWSK2;
        public String LIFNR;
        public String KUNNR;
        public Decimal KDIFF;
        public Decimal KWERT;
        public String KSTEU;
        public String KINAK;
        public String KOAID;
        public Int32 ZAEKO;
        public String KMXAW;
        public String KMXWR;
        public Double KFAKTOR;
        public String KDUPL;
        public Double KFAKTOR1;
        public String KZBZG;
        public Decimal KSTBS;
        public String KONMS;
        public String KONWS;
        public Decimal KAWRT_K;
        public String KWAEH;
        public Decimal KWERT_K;
        public String KFKIV;
        public String KVARC;
        public String KMPRS;
        public String PRSQU;
        public String VARCOND;
        public Decimal STUFE;
        public Decimal WEGXX;
        public String KTREL;
        public String MDFLG;
        public String TXJLV;
        public String KBFLAG;
        public Int32 KOLNR3;
        public String CPF_GUID;
        public String KAQTY;
    }
    public class ZMOV_QUERY_DET_FACT_LT_VBRK
    {
        public String MANDT;
        public String VBELN;
        public String FKART;
        public String FKTYP;
        public String VBTYP;
        public String WAERK;
        public String VKORG;
        public String VTWEG;
        public String KALSM;
        public String KNUMV;
        public String VSBED;
        public String FKDAT;
        public String BELNR;
        public Int32 GJAHR;
        public Int32 POPER;
        public String KONDA;
        public String KDGRP;
        public String BZIRK;
        public String PLTYP;
        public String INCO1;
        public String INCO2;
        public String EXPKZ;
        public String RFBSK;
        public String MRNKZ;
        public Decimal KURRF;
        public String CPKUR;
        public Int32 VALTG;
        public String VALDT;
        public String ZTERM;
        public String ZLSCH;
        public String KTGRD;
        public String LAND1;
        public String REGIO;
        public String COUNC;
        public String CITYC;
        public String BUKRS;
        public String TAXK1;
        public String TAXK2;
        public String TAXK3;
        public String TAXK4;
        public String TAXK5;
        public String TAXK6;
        public String TAXK7;
        public String TAXK8;
        public String TAXK9;
        public Decimal NETWR;
        public String ZUKRI;
        public String ERNAM;
        public String ERZET;
        public String ERDAT;
        public String STAFO;
        public String KUNRG;
        public String KUNAG;
        public String MABER;
        public String STWAE;
        public String EXNUM;
        public String STCEG;
        public String AEDAT;
        public String SFAKN;
        public String KNUMA;
        public String FKART_RL;
        public String FKDAT_RL;
        public String KURST;
        public String MSCHL;
        public String MANSP;
        public String SPART;
        public String KKBER;
        public String KNKLI;
        public String CMWAE;
        public Decimal CMKUF;
        public String HITYP_PR;
        public String BSTNK_VF;
        public String VBUND;
        public String FKART_AB;
        public String KAPPL;
        public String LANDTX;
        public String STCEG_H;
        public String STCEG_L;
        public String XBLNR;
        public String ZUONR;
        public Decimal MWSBK;
        public String LOGSYS;
        public String FKSTO;
        public String XEGDR;
        public String RPLNR;
        public String LCNUM;
        public String J_1AFITP;
        public String KURRF_DAT;
        public String AKWAE;
        public Decimal AKKUR;
        public String KIDNO;
        public String BVTYP;
        public Int32 NUMPG;
        public String BUPLA;
        public String VKONT;
        public String FKK_DOCSTAT;
        public String NRZAS;
        public String SPE_BILLING_IND;
        public String VTREF;
        public String FK_SOURCE_SYS;
        public String FKTYP_CRM;
        public String STGRD;
        public String VBTYP_EXT;
        public String J_1TPBUPL;
        public String INCOV;
        public String INCO2_L;
        public String INCO3_L;
        public String DPC_REL;
        public String MNDID;
        public String PAY_TYPE;
        public String SEPON;
        public String MNDVG;
        public String SPPAYM;
        public String SPPORD;
    }
    public class ZMOV_QUERY_DET_FACT_LT_VBRP
    {
        public String MANDT;
        public String VBELN;
        public Int32 POSNR;
        public Int32 UEPOS;
        public Decimal FKIMG;
        public String VRKME;
        public Decimal UMVKZ;
        public Decimal UMVKN;
        public String MEINS;
        public Decimal SMENG;
        public Decimal FKLMG;
        public Decimal LMENG;
        public Decimal NTGEW;
        public Decimal BRGEW;
        public String GEWEI;
        public Decimal VOLUM;
        public String VOLEH;
        public String GSBER;
        public String PRSDT;
        public String FBUDA;
        public Decimal KURSK;
        public Decimal NETWR;
        public String VBELV;
        public Int32 POSNV;
        public String VGBEL;
        public Int32 VGPOS;
        public String VGTYP;
        public String AUBEL;
        public Int32 AUPOS;
        public String AUREF;
        public String MATNR;
        public String ARKTX;
        public String PMATN;
        public String CHARG;
        public String MATKL;
        public String PSTYV;
        public String POSAR;
        public String PRODH;
        public String VSTEL;
        public String ATPKZ;
        public String SPART;
        public Int32 POSPA;
        public String WERKS;
        public String ALAND;
        public String WKREG;
        public String WKCOU;
        public String WKCTY;
        public String TAXM1;
        public String TAXM2;
        public String TAXM3;
        public String TAXM4;
        public String TAXM5;
        public String TAXM6;
        public String TAXM7;
        public String TAXM8;
        public String TAXM9;
        public String KOWRR;
        public String PRSFD;
        public String SKTOF;
        public Decimal SKFBP;
        public String KONDM;
        public String KTGRM;
        public String KOSTL;
        public String BONUS;
        public String PROVG;
        public String EANNR;
        public String VKGRP;
        public String VKBUR;
        public String SPARA;
        public String SHKZG;
        public String ERNAM;
        public String ERDAT;
        public String ERZET;
        public String BWTAR;
        public String LGORT;
        public String STAFO;
        public Decimal WAVWR;
        public Decimal KZWI1;
        public Decimal KZWI2;
        public Decimal KZWI3;
        public Decimal KZWI4;
        public Decimal KZWI5;
        public Decimal KZWI6;
        public Decimal STCUR;
        public String UVPRS;
        public String UVALL;
        public String EAN11;
        public String PRCTR;
        public String KVGR1;
        public String KVGR2;
        public String KVGR3;
        public String KVGR4;
        public String KVGR5;
        public String MVGR1;
        public String MVGR2;
        public String MVGR3;
        public String MVGR4;
        public String MVGR5;
        public String MATWA;
        public Decimal BONBA;
        public String KOKRS;
        public Int32 PAOBJNR;
        public Int32 PS_PSP_PNR;
        public String AUFNR;
        public String TXJCD;
        public Decimal CMPRE;
        public String CMPNT;
        public Int32 CUOBJ;
        public Int32 CUOBJ_CH;
        public String KOUPD;
        public Int32 UECHA;
        public String XCHAR;
        public String ABRVW;
        public String SERNR;
        public String BZIRK_AUFT;
        public String KDGRP_AUFT;
        public String KONDA_AUFT;
        public String LLAND_AUFT;
        public String MPROK;
        public String PLTYP_AUFT;
        public String REGIO_AUFT;
        public String VKORG_AUFT;
        public String VTWEG_AUFT;
        public String ABRBG;
        public String PROSA;
        public String UEPVW;
        public String AUTYP;
        public String STADAT;
        public String FPLNR;
        public Int32 FPLTR;
        public String AKTNR;
        public String KNUMA_PI;
        public String KNUMA_AG;
        public String PREFE;
        public Decimal MWSBP;
        public String AUGRU_AUFT;
        public String FAREG;
        public String UPMAT;
        public String UKONM;
        public Double CMPRE_FLT;
        public String ABFOR;
        public Double ABGES;
        public String J_1ARFZ;
        public String J_1AREGIO;
        public String J_1AGICD;
        public String J_1ADTYP;
        public String J_1ATXREL;
        public String J_1BCFOP;
        public String J_1BTAXLW1;
        public String J_1BTAXLW2;
        public String J_1BTXSDC;
        public Decimal BRTWR;
        public String WKTNR;
        public Int32 WKTPS;
        public String RPLNR;
        public String KURSK_DAT;
        public String WGRU1;
        public String WGRU2;
        public String KDKG1;
        public String KDKG2;
        public String KDKG3;
        public String KDKG4;
        public String KDKG5;
        public String VKAUS;
        public String J_1AINDXP;
        public String J_1AIDATEP;
        public String KZFME;
        public String MWSKZ;
        public String VERTT;
        public String VERTN;
        public String SGTXT;
        public String DELCO;
        public String BEMOT;
        public String RRREL;
        public Decimal AKKUR;
        public String WMINR;
        public String VGBEL_EX;
        public Int32 VGPOS_EX;
        public String LOGSYS;
        public String VGTYP_EX;
        public String J_1BTAXLW3;
        public String J_1BTAXLW4;
        public String J_1BTAXLW5;
        public String MSR_ID;
        public String MSR_REFUND_CODE;
        public String MSR_RET_REASON;
        public String NRAB_KNUMH;
        public Decimal NRAB_VALUE;
        public String DISPUTE_CASE;
        public String FUND_USAGE_ITEM;
        public String FARR_RELTYPE;
        public String CLAIMS_TAXATION;
        public String KURRF_DAT_ORIG;
        public String VGTYP_EXT;
        public String SGT_RCAT;
        public String SGT_SCAT;
        public Int32 AUFPL;
        public Int32 APLZL;
        public String DPCNR;
        public Int32 DCPNR;
        public Int32 DPNRB;
        public String PEROP_BEG;
        public String PEROP_END;
        public String FONDS;
        public String FISTL;
        public String FKBER;
        public String GRANT_NBR;
        public Int32 PRS_WORK_PERIOD;
        public String PPRCTR;
        public String PARGB;
        public Int32 AUFPL_OAA;
        public Int32 APLZL_OAA;
        public String CAMPAIGN;
        public String COMPREAS;
    }

}